config/routes.rb
Rails.application.routes.draw do
  resources :epitaphs, only: [:new, :create, :update, :index, :show, :edit] do
    post 'write', on: :new
    get 'share', on: :member
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root to: "high_voltage/pages#show", id: 'landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epitaph.rb
class Epitaph < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, :registerable, :rememberable, :trackable, :omniauth_providers => [:twitter]
  has_one :epitaph

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.nickname
    end
  end

  before_validation :generate_slug

  def to_param
    slug
  end

  private

  def generate_slug
    return if slug
    while self.class.where(slug: (self.slug = SecureRandom.urlsafe_base64(8))).count > 0
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/epitaphs_controller.rb
class EpitaphsController < ApplicationController

  def write
    if epitaph_params[:name].blank?
      redirect_to :root
      return
    end
    session[:name] = epitaph_params[:name]
    redirect_to new_epitaph_path
  end

  def new
    if session[:name].blank?
      redirect_to :root
      return
    end
    @epitaph = Epitaph.new name: session[:name]
  end

  def create
    session[:epitaph] = epitaph_params

    if current_user
      redirect_to epitaphs_path
      return
    end

    # User not logged in, send them off to do so
    store_location_for :user, epitaphs_path

    case params[:commit]
    when 'twitter' then redirect_to user_twitter_omniauth_authorize_path
    else
      # don't know how they got here. is error or someone messing with the form.
      # TODO: Raise a proper error here
      logger.error "Got a bad value for submit on POST #{epitaphs_path}: #{params[:commit].inspect}"
      redirect_to :root
    end
  end

  def show
    u = User.where(slug: params[:id].to_s).first!
    @epitaph = u && u.epitaph
    raise ActiveRecord::RecordNotFound unless @epitaph
  end

  def share
      show
  end

  def edit
      authenticate_user!
      @epitaph = current_user.epitaph
      if @epitaph.nil?
          redirect_to :root
          return
      end
  end

  def update
      authenticate_user!
      @epitaph = current_user.epitaph
      raise ActiveRecord::RecordNotFound unless @epitaph
      @epitaph.update!(epitaph_params)
      redirect_to epitaph_url(current_user)
  end

  # user will end up here after clicking "save" and going through login redirect dance
  def index
    if !current_user
      # TODO: this could redirect to a login page instead
      redirect_to :root
      return
    end

    # case we would normally expect
    if session[:epitaph] && session[:epitaph].respond_to?(:[])
      e = session.delete(:epitaph).with_indifferent_access
      @epitaph = Epitaph.find_or_initialize_by(user: current_user)
      @epitaph.name = e[:name]
      @epitaph.text = e[:text]
      @epitaph.save!
      logger.debug "Final epitaph: #{@epitaph.inspect}"
    end

    redirect_to epitaph_path(current_user)
  end


  private

  def epitaph_params
    params.fetch(:epitaph, {}).permit(:name, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    session["devise.twitter_data"] = request.env["omniauth.auth"]

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      set_flash_message(:error, :failure, :kind => "Twitter") if is_navigational_format?
      failure
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epitaphs_helper.rb
module EpitaphsHelper
end

app/views/epitaphs/_new_answer_left.html.erb
<div class="container">
    <div class="row no-gutters">
        <div class="<%= answer_id %> col-lg-4 col-md-6 col-sm-8 col-10">
            <div class="new-epitaph-answer new-epitaph-answer-left">
                <q><%= t "#{answer_id}-html", name: name %></q>
            </div>
        </div>
    </div>
</div>

app/views/epitaphs/_new_answer_right.html.erb
<div class="container">
    <div class="row no-gutters justify-content-end">
        <div class="<%= answer_id %> col-lg-4 col-md-6 col-sm-8">
            <div class="new-epitaph-answer new-epitaph-answer-right">
                <q><%= t "#{answer_id}-html", name: name %></q>
            </div>
        </div>
    </div>
</div>

app/views/epitaphs/_new_question.html.erb
<div class="container">
    <div class="row justify-content-center <%= question_id %>">
        <div class="d-flex flex-column align-items-center new-epitaph-question">
            <%= t "#{question_id}-html" %>
        </div>
    </div>
</div>

app/views/epitaphs/_tombstone.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="tombstone tombstone-1">
            <div class="epitaph-container">
                <%= yield %>
            </div>
        </div>
    </div>
</div>

app/views/epitaphs/_tombstone_name_text.html.erb
<%= render 'epitaphs/tombstone' do %>
    <h4>Here lies</h4>
    <h3><%= name %></h3>
    <h5><%= text %></h5>
<% end %>

app/views/epitaphs/edit.html.erb
<%= form_for @epitaph, url: epitaph_path(current_user), html: {class: 'themed-form tombstone-bg'} do |f| %>
  <div class="lighter fade-darker-short">

    <div class="container">
      <div class="row landing-header justify-content-center">
        <div class="col-12">
          <h4 class='text-primary'><%= t :landing_header %> </h4>
        </div>
      </div>
    </div>

    <%= render 'epitaphs/tombstone' do %>
        <h5>Here lies</h4>
        <%= f.label :name %>
        <h3><%= f.text_field :name, class: 'form-control', placeholder: Epitaph.human_attribute_name(:name) %></h3>
        <%= f.label :text %>
        <%= f.text_area :text, value: @epitaph.text, class: 'form-control', placeholder: t(:epitaph_placeholder) %>
    <% end %>
  </div>

  <div class="container">
    <div class="row justify-content-center show-epitaph-buttons">
      <div class="col-md-auto col-sm-6">
        <%= link_to t('cancel'), epitaph_url(current_user), class: 'btn', role: "button" %>
      </div>
      <div class="col-md-auto col-sm-6">
        <%= button_tag t(:save), class: 'btn' %>
      </div>
    </div>
  </div>
<% end %>

app/views/epitaphs/new.html.erb
<div class="fade-down-lighter">
    <div class="container">
        <div class="row justify-content-center new-epitaph-name">
            <h5><%= @epitaph.name %></h5>
        </div>
        <div class="row justify-content-center new-epitaph-lede">
            <h3><%= t 'new-epitaph-lede-html' %></h3>
        </div>
    </div>
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q1'} %>
</div>
<div class="lighter">
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q2'} %>
    <%= render partial: 'new_answer_left', locals: {answer_id: 'new-epitaph-a2-1', name: @epitaph.name} %>
    <%= render partial: 'new_answer_right', locals: {answer_id: 'new-epitaph-a2-2', name: @epitaph.name} %>
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q3'} %>
    <%= render partial: 'new_answer_left', locals: {answer_id: 'new-epitaph-a3', name: @epitaph.name} %>
</div>
<%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q4'} %>
<%= render partial: 'new_answer_right', locals: {answer_id: 'new-epitaph-a4-1', name: @epitaph.name} %>
<%= render partial: 'new_answer_left', locals: {answer_id: 'new-epitaph-a4-2', name: @epitaph.name} %>
<%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q5'} %>
<div class="fade-darkest">
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q6'} %>
</div>
<div class="darkest">
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-ellipses'} %>
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q7'} %>
    <%= render partial: 'new_answer_right', locals: {answer_id: 'new-epitaph-a7', name: @epitaph.name} %>
    <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-q8'} %>
</div>
<%= form_for @epitaph, html: {class: 'themed-form tombstone-bg'} do |f| %>
    <div class="fade-down-lighter fade-down-lighter-full lighter">
        <%= render partial: 'new_question', locals: {question_id: 'new-epitaph-end'} %>
        <%= render 'epitaphs/tombstone' do %>
            <h5>Here lies</h4>
            <h3><%= @epitaph.name %></h3>
            <%= f.hidden_field :name, value: @epitaph.name %>
            <%= f.label :text, class: 'sr-only' %>
            <%= f.text_area :text, value: @epitaph.text, class: 'form-control', placeholder: t(:epitaph_placeholder) %>
        <% end %>
    </div>

    <div class="new-epitaph-save container">
        <div class="row justify-content-center">
            <% if current_user %>
                <h6><%= t :save_yours %></h6>
            <% else %>
                <h6><%= t :save_yours_login_required %></h6>
            <% end %>
        </div>
        <div class="row justify-content-center">
            <% if current_user %>
                <%= button_tag t(:save), class: 'btn' %>
            <% else %>
                <%= button_tag t('twitter-submit-html'), class: 'btn', name: 'commit', value: 'twitter' %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/epitaphs/share.html.erb
<div class="lighter fade-darker-short share-epitaph-container">

    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <%= render partial: 'tombstone_name_text', locals: {name: @epitaph.name, text: @epitaph.text} %>
            </div>
            <div class="col-lg-8">
              <h4><%=t 'share_header' %></h4>
              <% if @epitaph.user == current_user %>
                <div><%=label_tag :share_link, t(:share_link) %><%= text_field_tag :share_link, epitaph_url(@epitaph.user), class: 'form-control' %></div>
              <% else %>
                <div><%= link_to t(:write_yours_from_share), root_path %>
              <% end %>
            </div>
        </div>
    </div>

</div>

<!--
<div id="threedeeplayland">
    <div oncontextmenu="return false;" id="viewerContext" style="width: 400px; height: 400px"></div>

    <%# divs required by openjscad %>
    <div id="errordiv" style="background: #fff; color: #000; margin 10px;">hello</div>
    <div id="parametersdiv" style="display: none;"></div>
    <div id="statusdiv"></div>

    <script type="text/javascript">
    var gProcessor = null; // required by OpenJScad.org

    function loadProcessor() {
        gProcessor = new OpenJsCad.Processor(document.getElementById("viewerContext"),
            { useAsync: false,
              libraries:["<%= javascript_path 'threedee' %>"],

              viewer: {
                       plate: { draw: false },
                       camera: {position: {x:   0,y:  0,z:  200},
                                clip:     {min: 0.5,  max: 1000}
                               },
                       axis: {draw: false},
                   },
             directParameters: {
                 lastName: '',
                 firstName: '<%= j(@epitaph.name) %>',
                 dateSpan: '',
                 epitaph: '<%= j(@epitaph.text) %>'}
            });
        loadJSCAD();
    }


    function loadJSCAD() {
        // var filepath = "/assets/threedee/tombstone.jscad";
        var filepath = "<%= asset_path("threedee/tombstone.jscad") %>";
        var xhr = new XMLHttpRequest();
        xhr.open("GET", filepath, true);
        gProcessor.setStatus("");

        xhr.onload = function() {
            var source = this.responseText;
            if (filepath.match(/\.jscad$/i) || filepath.match(/\.js$/i)) {
                gProcessor.setStatus("");
                gProcessor.setJsCad(source, filepath);
            }
        }
        xhr.send();
    }

    $(document).ready(loadProcessor());
</script>


</div>
-->

app/views/epitaphs/show.html.erb
<div class="lighter fade-darker-short">

    <div class="container">
        <div class="row landing-header justify-content-center">
            <div class="col-12">
                <h4 class='text-primary'><%= t :landing_header %> </h4>
            </div>
        </div>
    </div>

    <%= render partial: 'tombstone_name_text', locals: {name: @epitaph.name, text: @epitaph.text} %>
</div>

<div class="container">
    <div class="row justify-content-center show-epitaph-buttons">
        <% if @epitaph.user == current_user %>
            <div class="col-md-auto col-sm-6">
                <%= link_to t('edit_epitaph'), edit_epitaph_url(current_user), class: 'btn', role: "button" %>
            </div>
            <div class="col-md-auto col-sm-6">
                <%= link_to t('share_yours'), share_epitaph_url(current_user), class: 'btn', role: "button" %>
            </div>
        <% else %>
            <div class="col-12">
                <%= link_to t(:write_yours_from_share), root_path, class: 'btn', role: "button" %>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  Signed in as <%=current_user.username%>
  <%= link_to "Sign out", destroy_user_session_path %>
<% else %>
  <%= link_to "Sign in with Twitter", user_twitter_omniauth_authorize_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Soon</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "threedee" %>

  </head>
  <body>
    <nav class="navbar">
      <span class="navbar-brand"><%=image_tag 'Logo.png'%> SOON</span>
    </nav>
    <div class="container">
      <% if notice %>
      <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-92549847-1', 'auto');
      ga('send', 'pageview');

    </script>
    <% end %>
  </body>
</html>

app/views/pages/landing.html.erb
<div class="lighter fade-down-lightest">
    <div class="container">
        <div class="row landing-header justify-content-center">
            <div class="col-12">
                <h4 class='text-primary'><%= t :landing_header %> </h4>
            </div>
        </div>
    </div>
    <div class="fade-darker landing-tombstone-container">
        <%= render partial: 'epitaphs/tombstone_name_text', locals: {name: 'Will Rogers', text: "I never met a man I didn’t like"} %>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <%=t 'landing-content-html'%>
        </div>
        <div class="col-lg-6 landing-form">
            <%= form_for Epitaph.new, url: write_new_epitaph_path, html: {class: 'themed-form'} do |f| %>
                <div class="form-group row">
                    <%= f.label :name, class: 'col-2 col-form-label col-form-label-lg'%>
                    <%= f.text_field :name, value: session[:name], class: 'form-control form-control-lg col-8' %>
                </div>
                <%= button_tag t('write_yours_submit'), class: 'btn btn-large' %>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/teaser.html.erb
<div style="margin: 0 15px">
  <div class="row landing-header justify-content-center" style="margin-top: 35vh;">
    <h1 class="text-primary">Death is coming.</h1>
  </div>
  <div class="row justify-content-center">
    <p class="lead">What will your epitaph say? Will it be true?</p>
  </div>
  <div class="row fixed-bottom justify-content-center">
    <div class="inner">
      <p>contact@soon.rip</p>
    </div>
  </div>
</div>